// tslint:disable
/**
 * Track the Gathering API
 * Track the Gathering API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI } from '../runtime';
import type { OperationOpts, HttpQuery } from '../runtime';

export interface UserControllerGetUsersRequest {
  take?: number;
  page?: number;
}

/**
 * no description
 */
export class UsersApi extends BaseAPI {
  /**
   */
  userControllerGetUsers({
    take,
    page,
  }: UserControllerGetUsersRequest): Observable<object>;
  userControllerGetUsers(
    { take, page }: UserControllerGetUsersRequest,
    opts?: OperationOpts
  ): Observable<AjaxResponse<object>>;
  userControllerGetUsers(
    { take, page }: UserControllerGetUsersRequest,
    opts?: OperationOpts
  ): Observable<object | AjaxResponse<object>> {
    const query: HttpQuery = {};

    if (take != null) {
      query['take'] = take;
    }
    if (page != null) {
      query['page'] = page;
    }

    return this.request<object>(
      {
        url: '/api/users',
        method: 'GET',
        query,
      },
      opts?.responseOpts
    );
  }
}
