name: Deploy to Heroku

on:
  push:
    branches:
      - development

permissions:
  actions: read
  contents: read

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup build env
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci
      - run: npx nx affected -t lint
      - run: npx nx affected -t test--configuration=ci
      - run: npx nx affected -t build
      # - run: npx nx affected -t e2e-ci

      - name: Build API Docker container, push it to Heroku container registry and deploy
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ vars.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ vars.HEROKU_APP_NAME }}
          dockerfile_directory: ./apps/api
          dockerfile_name: Dockerfile
          docker_options: "--no-cache"
          process_type: web