name: Deploy API to Heroku

on:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup build env
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci
      # TODO: change these run commands to use affected
      # - run: npx nx run api:lint
      # - run: npx nx run api:test --configuration=ci
      - run: npx nx run api:build
      - run: npx nx run api:"migrate:build"
      # - run: npx nx run-many -t e2e-ci --base=${{ github.ref_name }}
      

      - name: Build API Docker container, push it to Heroku container registry and deploy
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ vars.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ vars.HEROKU_APP_NAME }}
          dockerfile_directory: ./apps/api
          dockerfile_name: Dockerfile
          docker_options: "--no-cache"
          process_type: web